### ISSUE TITLE
Rollup failed to resolve plugin.client.ts

### ISSUE THREAD

**Issue by davireis** [nuxt-community/nuxt-logrocket#328] opened 2023-01-07 18:02 UTC
Giving this a try in my nuxt 3 setup, and I get the following when I run "pnpm build":

`[vite]: Rollup failed to resolve import "/workspaces/trash/guis/web/node_modules/nuxt-logrocket/dist/runtime/plugin.client.ts" from "virtual:nuxt:/workspaces/trash/guis/web/.nuxt/plugins/client.mjs".`

I have the same problem using npm instead of pnpm.

Looking at the directory, I have `plugin.client.d.ts` and `plugin.client.mjs`, but no `plugin.client.ts`.

**Comment by davireis** [comment] 2023-01-21 08:16
Gave the new 2.0.4 version a try, and now it seems I get a hardcoded path error:

```ERROR  Error while requiring module nuxt-logrocket: Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/farzad/projects/oss/nuxt-logrocket/node_modules/jiti/lib/index.js' imported from /workspaces/trash/guis/web/node_modules/nuxt-logrocket/dist/module.mjs```

**Comment by farzadso** [comment] 2023-05-30 13:20
Dupe of https://github.com/nuxt-community/nuxt-logrocket/issues/327

**Closed by farzadso** 2023-05-30 13:20 UTC
